export const REAL_IMAGES: Record<string, { src: string; fit: "cover" | "contain" }> = {
  P01: { src: "/images/p01-qnh.jpg", fit: "cover" },
  P02: { src: "/images/p02-summer.jpg", fit: "cover" },
  P03: { src: "/images/p03-pnj.jpg", fit: "cover" },
  P04: { src: "/images/p04-energy.jpg", fit: "cover" },
  P05: { src: "/images/p05-buv.jpg", fit: "cover" },
  P06: { src: "/images/p06-hapacol.jpg", fit: "cover" },
  P07: { src: "/images/p07-boardgame.jpg", fit: "cover" },
  P11: { src: "/images/p11-gnkn.jpg", fit: "cover" },
  P12: { src: "/images/p12-folk-western.jpg", fit: "cover" },
  P13: { src: "/images/p13-chart.jpg", fit: "contain" },
  P14: { src: "/images/p14-magazine.jpg", fit: "cover" },
  P15: { src: "/images/p15-photoshoots.jpg", fit: "cover" },
  P16: { src: "/images/p16-patriotic-rap.jpg", fit: "cover" },
  P18: { src: "/images/p18-google-doodle.gif", fit: "cover" },
  P19: { src: "/images/p19-ikea.jpg", fit: "cover" },
  P20: { src: "/images/p20-chart.jpg", fit: "contain" },
  P21: { src: "/images/p21-vinamilk.jpg", fit: "cover" },
  P22: { src: "/images/p22-accept-differences.jpg", fit: "cover" },
  P23: { src: "/images/p23-rmit-social.jpg", fit: "cover" },
  P24: { src: "/images/p24-mbe.jpg", fit: "cover" },
  P25: { src: "/images/p25-empacts.jpg", fit: "cover" },
  P28: { src: "/images/p28-vinfast.jpg", fit: "cover" },
  P31: { src: "/images/p31-be-local-web.jpg", fit: "cover" },
};
